spring.config.import=optional:file:.env[.properties]

# Exchange y Queues del modulo payment
rabbitmq.exchange.payment=${RABBITMQ_EXCHANGE_PAYMENT:payment.exchange}
rabbitmq.queue.payment.cashreceipt.create=${RABBITMQ_QUEUE_PAYMENT_CASHRECEIPT_CREATE:payment.cashreceipt.create.queue}
rabbitmq.queue.payment.cashreceipt.cancel=${RABBITMQ_QUEUE_PAYMENT_CASHRECEIPT_CANCEL:payment.cashreceipt.cancel.queue}
rabbitmq.routing-key.payment.cashreceipt.create=${RABBITMQ_ROUTING_KEY_PAYMENT_CASHRECEIPT_CREATE:payment.cashreceipt.create}
rabbitmq.routing-key.payment.cashreceipt.cancel=${RABBITMQ_ROUTING_KEY_PAYMENT_CASHRECEIPT_CANCEL:payment.cashreceipt.cancel}
